# Generated by Django 3.2.11 on 2022-10-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegeapp', '0002_auto_20221014_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='adstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Registartion'), (3, 'AddressDetail'), (4, 'ReservationDetail'), (5, 'ScholarshipDetail'), (6, 'AcademicDetail'), (7, 'DeclarationStudent')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='declarationstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarshipdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
