# Generated by Django 3.2.11 on 2022-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_auto_20221015_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetail',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetail',
            name='academics',
            field=models.TextField(blank=True, default={'SGPA/CGPA': '', 'board': '', 'class/course': '', 'marks-obtained': '', 'percentage': '', 'total-marks': ''}, null=True),
        ),
    ]
