# Generated by Django 3.2.11 on 2022-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_declarationstudent_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprocess',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='adstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Registartion'), (3, 'Address'), (4, 'Reservation'), (5, 'Scholarship'), (6, 'Academic'), (7, 'Declaration'), (8, 'Give Approval')], default=1, null=True),
        ),
    ]
