# Generated by Django 3.2.11 on 2022-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_auto_20221021_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationprocess',
            name='checkedby',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='examinationprocess',
            name='dated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationprocess',
            name='signhod',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='examinationprocess',
            name='signstudent',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='examinationprocess',
            name='signverifier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
