# Generated by Django 3.2.11 on 2022-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0011_commentexm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='adstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Registartion'), (3, 'Address'), (4, 'Reservation'), (5, 'Scholarship'), (6, 'Academic'), (7, 'Declaration'), (8, 'Approval')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='commentadm',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='commentexm',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected'), (4, 'Payment Pending'), (5, 'Payment Completed')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='examinationprocess',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected'), (4, 'Payment Pending'), (5, 'Payment Completed')], null=True),
        ),
    ]
