# Generated by Django 3.2.11 on 2022-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0012_auto_20221026_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetail',
            name='belong_to',
            field=models.IntegerField(blank=True, choices=[(1, 'URBAN'), (2, 'RURAL'), (3, 'TRIBAL')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'OPEN'), (2, 'OBC'), (3, 'SC'), (4, 'ST'), (5, 'SBC'), (6, 'ESBC'), (7, 'VJ-DT'), (8, 'NT1'), (9, 'NT2'), (10, 'NT3'), (11, 'EWS')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='ftad',
            field=models.IntegerField(blank=True, choices=[(1, 'FIRST YEAR'), (2, 'DIRECT SECOND YEAR')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='residential_status',
            field=models.IntegerField(blank=True, choices=[(1, 'MS'), (2, 'OMS'), (3, 'J & K')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetail',
            name='seat_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CAP'), (2, 'IL'), (3, 'MINIORITY'), (4, 'j & K'), (5, 'ACAP'), (6, 'TFWS')], default=1, null=True),
        ),
    ]
