# Generated by Django 4.1.3 on 2022-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0013_auto_20221031_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declarationstudent',
            old_name='check',
            new_name='checked',
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected'), (4, 'Payment Pending'), (5, 'Payment Completed')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='commentadm',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verfied'), (3, 'Rejected'), (4, 'Payment Pending'), (5, 'Payment Completed')], default=1, null=True),
        ),
    ]
