# Generated by Django 3.2.11 on 2022-11-10 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegeapp', '0014_rename_check_declarationstudent_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocess',
            name='adstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Registartion'), (3, 'Address'), (4, 'Reservation'), (5, 'Scholarship'), (6, 'Academic'), (7, 'Upload File'), (8, 'Declaration'), (8, 'Upload File'), (9, 'Approval')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='UploadFileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True, default={'object': [{'filename': '', 'uploadfile': ''}]}, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
