# Generated by Django 3.2.11 on 2022-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0015_auto_20221110_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionprocess',
            name='adstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Registartion'), (3, 'Address'), (4, 'Reservation'), (5, 'Scholarship'), (6, 'Academic'), (7, 'Upload File'), (8, 'Declaration'), (9, 'Approval')], default=1, null=True),
        ),
    ]
