# Generated by Django 3.2.11 on 2022-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0016_auto_20221112_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp',
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
